name: restaurant_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.6
  get_storage: ^2.1.1
  firebase_messaging: ^12.0.3
  flutter_local_notifications: ^9.9.1
  flutter: 
    sdk: flutter
  http: ^0.13.5
  permission_handler: ^10.2.0

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  ffi: ^2.0.1

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/

